version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Forcing server/app.js to use process.env.PORT (EB 8081)..."
      - |
        if grep -q "app\.listen" server/app.js; then
          sed -i 's/app\.listen.*/app.listen(process.env.PORT || 3000);/g' server/app.js
          echo "Patched existing app.listen"
        else
          echo "app.listen not found - appending to end of file"
          echo "" >> server/app.js
          echo "const PORT = process.env.PORT || 3000;" >> server/app.js
          echo "app.listen(PORT, () => console.log('Server running on port ' + PORT));" >> server/app.js
        fi
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
