version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing test dependencies..."
      - npm install

  build:
    commands:
      - echo "Running tests..."
      - npm test || echo "No tests found - continuing pipeline"
  artifacts:
  files:
    - '**/*'
  discard-paths: yes
