version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18 # ES6 compatible
    commands:
      - npm install -g @babel/core @babel/cli # For ES6 transpile
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo "Building ES6 app..."
      - npm run build # Transpile to dist-server
artifacts:
  files:
    - "**/*"
  base-directory: dist-server # EB needs transpiled code
