version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Patching port in server/app.js for EB (8081)..."
      - sed -i 's/app\.listen([0-9]\+)/app.listen(process.env.PORT || 3000)/g' server/app.js || echo "No hard-coded port found"
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
