version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Replacing server/app.js with minimal working server..."
      - |
        cat > server/app.js << 'EOF'
        const express = require('express');
        const path = require('path');
        const app = express();

        // Serve static files
        app.use(express.static(path.join(__dirname, '../public')));

        // API route with student ID
        app.get('/api', (req, res) => {
          res.json({ message: 'My Student ID is 21920794. Welcome to Express' });
        });

        // Fallback: serve index.html
        app.get('*', (req, res) => {
          res.sendFile(path.join(__dirname, '../public/index.html'));
        });

        // Start server on EB port
        const PORT = process.env.PORT || 3000;
        app.listen(PORT, () => {
          console.log('Server running on port ' + PORT);
        });
        EOF
      - echo "server/app.js replaced"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
