version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Ensuring server/app.js has app.listen() with process.env.PORT..."
      - |
        if ! grep -q "app\.listen" server/app.js; then
          echo "" >> server/app.js
          echo "const PORT = process.env.PORT || 3000;" >> server/app.js
          echo "app.listen(PORT, () => console.log('Server running on port ' + PORT));" >> server/app.js
          echo "Added app.listen()"
        else
          sed -i 's/app\.listen.*/app.listen(process.env.PORT || 3000, () => console.log("Server running on port " + (process.env.PORT || 3000)));/g' server/app.js
          echo "Patched existing app.listen()"
        fi
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
